version: '3'

services:
  db:
    image: mariadb:10.4
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./db-import:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wptest
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes:
        - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wptest

networks:
  wptest:

volumes:
  db-data: {}
